	document.writeln("<html>");
	document.writeln("<head>");
	document.writeln("<title>导航<\/title>");
	document.writeln("<meta http-equiv=\"Content-Type\" content=\"text\/html; charset=gb2312\">");
	document.writeln("<style type=\"text\/css\">");
	document.writeln("<!--");
	document.writeln(".dh0707 {  font-family: \"宋体\"; font-size: 12px; line-height: 18px; color: #FFFFFF; text-decoration: none}");
	document.writeln("a:hover { text-decoration: underline}");
	document.writeln("td {  font-family: \"宋体\"; font-size: 12px; text-decoration: none}");
	document.writeln("-->");
	document.writeln("<\/style>");
	document.writeln("<\/head>");
	document.writeln("");
	document.writeln("<body bgcolor=\"#FFFFFF\" text=\"#000000\" leftmargin=\"0\" topmargin=\"0\">");
	document.writeln("<table id=\"top_table\" name=\"top_table\"  width=\"849\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">");
	document.writeln("  <tr> ");
	document.writeln("    <td height=\"20\" bgcolor=\"052A70\" align=\"center\">");
	document.writeln("      <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">");
	document.writeln("        <tr align=\"center\"> ");
	document.writeln("          <td width=\"73\" height=\"20\"> <a href=\"http:\/\/www.xinhuanet.com\/newscenter\" class=\"dh0707\">新闻中心<\/a><a href=\"http:\/\/www.xinhuanet.com\/politics\/\"><\/a><a href=\"http:\/\/www.xinhuanet.com\/world\"><\/a> ");
	document.writeln("          <\/td>");
	document.writeln("          <td width=\"73\"> <a href=\"http:\/\/www.xinhuanet.com\/focus\" class=\"dh0707\">焦点网谈<\/a> ");
	document.writeln("          <\/td>");
	document.writeln("          <td width=\"73\"> <a href=\"http:\/\/www.xinhuanet.com\/local\/\" class=\"dh0707\">地方联播<\/a> ");
	document.writeln("          <\/td>");
	document.writeln("          <td width=\"50\"> <a href=\"http:\/\/www.xinhuanet.com\/politics\/\" class=\"dh0707\">时政<\/a> ");
	document.writeln("          <\/td>");
	document.writeln("          <td width=\"50\"> <a href=\"http:\/\/www.xinhuanet.com\/world\" class=\"dh0707\">国际<\/a> ");
	document.writeln("          <\/td>");
	document.writeln("          <td width=\"50\"> <a href=\"http:\/\/www.xinhuanet.com\/legal\" class=\"dh0707\">法治<\/a> ");
	document.writeln("          <\/td>");
	document.writeln("          <td width=\"50\"><a href=\"http:\/\/www.xinhuanet.com\/video\" class=\"dh0707\">网视<\/a><\/td>");
	document.writeln("          <td width=\"50\"><a href=\"http:\/\/www.xinhuanet.com\/forum\" class=\"dh0707\">论坛<\/a><\/td>");
	document.writeln("          <td width=\"50\" height=\"20\"> <a href=\"http:\/\/www.xinhuanet.com\/fortune\" class=\"dh0707\">财经<\/a> ");
	document.writeln("          <\/td>");
	document.writeln("          <td width=\"50\"> <a href=\"http:\/\/www.xinhuanet.com\/auto\/\" class=\"dh0707\">汽车<\/a> ");
	document.writeln("          <\/td>");
	document.writeln("          <td width=\"50\"> <a href=\"http:\/\/www.xinhuanet.com\/sports\" class=\"dh0707\">体育<\/a> ");
	document.writeln("          <\/td>");
	document.writeln("          <td width=\"50\"> <a href=\"http:\/\/www.xinhuanet.com\/ent\" class=\"dh0707\">文娱<\/a> ");
	document.writeln("          <\/td>");
	document.writeln("          <td width=\"50\"> <a href=\"http:\/\/www.xinhuanet.com\/edu\" class=\"dh0707\">教育<\/a> ");
	document.writeln("          <\/td>");
	document.writeln("          <td width=\"50\"> <a href=\"http:\/\/www.xinhuanet.com\/shuhua\/\" class=\"dh0707\">书画<\/a> ");
	document.writeln("          <\/td>");
	document.writeln("          <td width=\"50\"> <a href=\"http:\/\/www.xinhuanet.com\/health\/\" class=\"dh0707\">健康<\/a> ");
	document.writeln("          <\/td>");
	document.writeln("          <td width=\"50\"> <a href=\"http:\/\/www.xinhuanet.com\/ziliao\/\" class=\"dh0707\">资料<\/a> ");
	document.writeln("          <\/td>");
	document.writeln("          <td width=\"50\"> <a href=\"http:\/\/www.xinhuanet.com\/mobile\/sjxmt.htm\" class=\"dh0707\">WAP&nbsp;<\/a><\/td>");
	document.writeln("        <\/tr>");
	document.writeln("      <\/table>");
	document.writeln("    <\/td>");
	document.writeln("  <\/tr>");
	document.writeln("  <tr>");
	document.writeln("    <td height=\"1\" bgcolor=\"2C5193\" align=\"center\"><\/td>");
	document.writeln("  <\/tr>");
	document.writeln("  <tr>");
	document.writeln("    <td height=\"20\" bgcolor=\"052A70\" align=\"center\">");
	document.writeln("      <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">");
	document.writeln("        <tr align=\"center\"> ");
	document.writeln("          <td width=\"73\" height=\"20\"> <a href=\"http:\/\/www.xinhuanet.com\/politics\/gcdt.htm\" class=\"dh0707\">高层动态<\/a> ");
	document.writeln("          <\/td>");
	document.writeln("          <td width=\"73\"> <a href=\"http:\/\/www.xinhuanet.com\/comments\/\" class=\"dh0707\">新华网评<\/a> ");
	document.writeln("          <\/td>");
	document.writeln("          <td width=\"73\"> <a href=\"http:\/\/www.xinhuanet.com\/tai_gang_ao\" class=\"dh0707\">港&nbsp;澳&nbsp;台<\/a> ");
	document.writeln("          <\/td>");
	document.writeln("          <td width=\"50\"> <a href=\"http:\/\/www.xinhuanet.com\/lianzheng\/\" class=\"dh0707\">廉政<\/a> ");
	document.writeln("          <\/td>");
	document.writeln("          <td width=\"50\"> <a href=\"http:\/\/www.xinhuanet.com\/mil\" class=\"dh0707\">军事<\/a> ");
	document.writeln("          <\/td>");
	document.writeln("          <td width=\"50\"> <a href=\"http:\/\/www.xinhuanet.com\/society\" class=\"dh0707\">社会<\/a> ");
	document.writeln("          <\/td>");
	document.writeln("          <td width=\"50\"><a href=\"http:\/\/www.xinhuanet.com\/zhibo\" class=\"dh0707\">直播<\/a><\/td>");
	document.writeln("          <td width=\"50\"><a href=\"http:\/\/blog.xinhuanet.com\/\" class=\"dh0707\">博客<\/a><\/td>");
	document.writeln("          <td height=\"20\" width=\"50\"> <a href=\"http:\/\/www.xinhuanet.com\/stock\" class=\"dh0707\">证券<\/a> ");
	document.writeln("          <\/td>");
	document.writeln("          <td width=\"50\"> <a href=\"http:\/\/www.xinhuanet.com\/house\" class=\"dh0707\">房产<\/a> ");
	document.writeln("          <\/td>");
	document.writeln("          <td width=\"50\"> <a href=\"http:\/\/www.xinhuanet.com\/olympics\/\" class=\"dh0707\">奥运<\/a> ");
	document.writeln("          <\/td>");
	document.writeln("          <td width=\"50\"> <a href=\"http:\/\/www.xinhuanet.com\/audio\/\" class=\"dh0707\">音乐<\/a> ");
	document.writeln("          <\/td>");
	document.writeln("          <td width=\"50\"> <a href=\"http:\/\/www.xinhuanet.com\/school\" class=\"dh0707\">校园<\/a> ");
	document.writeln("          <\/td>");
	document.writeln("          <td width=\"50\"> <a href=\"http:\/\/www.xinhuanet.com\/collection\" class=\"dh0707\">收藏<\/a> ");
	document.writeln("          <\/td>");
	document.writeln("          <td width=\"50\"> <a href=\"http:\/\/www.xinhuanet.com\/life\" class=\"dh0707\">生活<\/a> ");
	document.writeln("          <\/td>");
	document.writeln("          <td width=\"50\"> <a href=\"http:\/\/www.xinhuanet.com\/newscenter\/topic2007\/\" class=\"dh0707\">专题<\/a> ");
	document.writeln("          <\/td>");
	document.writeln("          <td width=\"50\"> <a href=\"http:\/\/www.xinhuanet.com\/mobile\/sjbcxb\/\" class=\"dh0707\">手机报<\/a><\/td>");
	document.writeln("        <\/tr>");
	document.writeln("      <\/table>");
	document.writeln("    <\/td>");
	document.writeln("  <\/tr>");
	document.writeln("  <tr>");
	document.writeln("    <td height=\"1\" bgcolor=\"2C5193\" align=\"center\"><\/td>");
	document.writeln("  <\/tr>");
	document.writeln("  <tr>");
	document.writeln("    <td height=\"20\" bgcolor=\"052A70\" align=\"center\">");
	document.writeln("      <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">");
	document.writeln("        <tr align=\"center\"> ");
	document.writeln("          <td width=\"73\" height=\"20\"> <a href=\"http:\/\/www.xinhuanet.com\/politics\/rsrm.htm\" class=\"dh0707\">人事任免<\/a> ");
	document.writeln("          <\/td>");
	document.writeln("          <td width=\"73\"> <a href=\"http:\/\/www.xinhuanet.com\/politics\/shidian.htm\" class=\"dh0707\">新华视点<\/a> ");
	document.writeln("          <\/td>");
	document.writeln("          <td width=\"73\"> <a href=\"http:\/\/www.xinhuanet.com\/internet\/\" class=\"dh0707\">互&nbsp;联&nbsp;网<\/a> ");
	document.writeln("          <\/td>");
	document.writeln("          <td width=\"50\"> <a href=\"http:\/\/www.xinhuanet.com\/theory\/\" class=\"dh0707\">理论<\/a> ");
	document.writeln("          <\/td>");
	document.writeln("          <td width=\"50\"> <a href=\"http:\/\/www.xinhuanet.com\/overseas\/\" class=\"dh0707\">华人<\/a> ");
	document.writeln("          <\/td>");
	document.writeln("          <td width=\"50\"> <a href=\"http:\/\/www.xinhuanet.com\/newmedia\" class=\"dh0707\">传媒<\/a> ");
	document.writeln("          <\/td>");
	document.writeln("          <td width=\"50\"><a href=\"http:\/\/www.xinhuanet.com\/media\/zxft.htm\" class=\"dh0707\">访谈<\/a><\/td>");
	document.writeln("          <td width=\"50\"><a href=\"http:\/\/www.xinhuanet.com\/photo\" class=\"dh0707\">图片<\/a><\/td>");
	document.writeln("          <td height=\"20\" width=\"50\"> <a href=\"http:\/\/www.xinhuanet.com\/tech\" class=\"dh0707\">科技<\/a> ");
	document.writeln("          <\/td>");
	document.writeln("          <td width=\"50\"> <a href=\"http:\/\/www.xinhuanet.com\/employment\" class=\"dh0707\">职场<\/a> ");
	document.writeln("          <\/td>");
	document.writeln("          <td width=\"50\"> <a href=\"http:\/\/www.xinhuanet.com\/environment\" class=\"dh0707\">环保<\/a> ");
	document.writeln("          <\/td>");
	document.writeln("          <td width=\"50\"> <a href=\"http:\/\/www.xinhuanet.com\/lady\" class=\"dh0707\">女性<\/a> ");
	document.writeln("          <\/td>");
	document.writeln("          <td width=\"50\"> <a href=\"http:\/\/www.xinhuanet.com\/book\" class=\"dh0707\">读书<\/a> ");
	document.writeln("          <\/td>");
	document.writeln("          <td width=\"50\"> <a href=\"http:\/\/www.xinhuanet.com\/travel\" class=\"dh0707\">旅游<\/a> ");
	document.writeln("          <\/td>");
	document.writeln("          <td width=\"50\"> <a href=\"http:\/\/www.xinhuanet.com\/food\" class=\"dh0707\">美食<\/a> ");
	document.writeln("          <\/td>");
	document.writeln("          <td width=\"50\"> <a href=\"http:\/\/www.xinhuanet.com\/graphics\" class=\"dh0707\">图表<\/a> ");
	document.writeln("          <\/td>");
	document.writeln("          <td width=\"50\">&nbsp;&nbsp;&nbsp;&nbsp;<\/td>");
	document.writeln("        <\/tr>");
	document.writeln("      <\/table>");
	document.writeln("    <\/td>");
	document.writeln("  <\/tr>");
	document.writeln("<\/table>");
	document.writeln("<\/body>");
	document.writeln("<\/html>");
	document.writeln("");

	document.writeln("<script type='text/javascript'>try{window.clearInterval(time);}catch(e){} time = window.setInterval('clear_top(\"top_table\")', 500); function clear_top(name) { 	if(document.readyState!='complete') 		return; 			window.clearInterval(time); 		listTable_top = document.getElementsByName(name);		if(listTable_top!=null && listTable_top.length > 1)		{ 		for(i=listTable_top.length-1; i!=0; i--)				{			 			_element = listTable_top[i];	       			_parentElement = _element.parentNode;    	     			if(_parentElement)			 			{  				_parentElement.removeChild(_element);        				}				}		}  }	</script>");

